-- ============================================
-- CAMPOS FALTANTES PARA EL SISTEMA TECNOTALLER
-- ============================================

-- 1. TABLA CLIENTES - Agregar campo para evaluaciones y observaciones
ALTER TABLE CLIENTES
ADD (
    EVALUACION NUMBER (2, 1) DEFAULT 0 CHECK (
        EVALUACION >= 0
        AND EVALUACION <= 5
    ),
    OBSERVACIONES CLOB,
    FECHA_ULTIMA_COMPRA DATE,
    TOTAL_COMPRAS NUMBER (10, 2) DEFAULT 0
);

-- 2. TABLA VEHICULOS - Campos para mejor gestión
ALTER TABLE VEHICULOS
ADD (
    COLOR VARCHAR2 (50),
    NUMERO_MOTOR VARCHAR2 (100),
    NUMERO_CHASIS VARCHAR2 (100),
    FECHA_ULTIMA_REVISION DATE,
    ESTADO_VEHICULO VARCHAR2 (20) DEFAULT 'ACTIVO' CHECK (
        ESTADO_VEHICULO IN (
            'ACTIVO',
            'EN_REPARACION',
            'INACTIVO'
        )
    ),
    OBSERVACIONES CLOB
);

-- 3. TABLA CITAS - Campos adicionales para mejor control
ALTER TABLE CITAS
ADD (
    DURACION_ESTIMADA NUMBER (3) DEFAULT 60, -- minutos
    COSTO_ESTIMADO NUMBER (10, 2),
    PRIORIDAD VARCHAR2 (10) DEFAULT 'NORMAL' CHECK (
        PRIORIDAD IN (
            'BAJA',
            'NORMAL',
            'ALTA',
            'URGENTE'
        )
    ),
    OBSERVACIONES_CLIENTE CLOB,
    OBSERVACIONES_TECNICO CLOB
);

-- 4. TABLA PRODUCTOS - Sistema de stock más completo
ALTER TABLE PRODUCTOS
ADD (
    STOCK_ACTUAL NUMBER (10, 2) DEFAULT 0,
    UNIDAD_MEDIDA VARCHAR2 (20) DEFAULT 'UNIDAD',
    PRECIO_COMPRA NUMBER (10, 2),
    MARGEN_GANANCIA NUMBER (5, 2) DEFAULT 0,
    FECHA_VENCIMIENTO DATE,
    UBICACION_ALMACEN VARCHAR2 (100),
    ESTADO_PRODUCTO VARCHAR2 (20) DEFAULT 'ACTIVO' CHECK (
        ESTADO_PRODUCTO IN (
            'ACTIVO',
            'INACTIVO',
            'DESCONTINUADO'
        )
    ),
    OBSERVACIONES CLOB
);

-- 5. TABLA PROVEEDORES - Sistema de evaluaciones
ALTER TABLE PROVEEDORES
ADD (
    EVALUACION_CALIDAD NUMBER (2, 1) DEFAULT 0 CHECK (
        EVALUACION_CALIDAD >= 0
        AND EVALUACION_CALIDAD <= 5
    ),
    EVALUACION_TIEMPO NUMBER (2, 1) DEFAULT 0 CHECK (
        EVALUACION_TIEMPO >= 0
        AND EVALUACION_TIEMPO <= 5
    ),
    EVALUACION_PRECIO NUMBER (2, 1) DEFAULT 0 CHECK (
        EVALUACION_PRECIO >= 0
        AND EVALUACION_PRECIO <= 5
    ),
    EVALUACION_GENERAL NUMBER (2, 1) DEFAULT 0 CHECK (
        EVALUACION_GENERAL >= 0
        AND EVALUACION_GENERAL <= 5
    ),
    FECHA_ULTIMA_COMPRA DATE,
    TOTAL_COMPRAS NUMBER (10, 2) DEFAULT 0,
    OBSERVACIONES CLOB,
    ESTADO_PROVEEDOR VARCHAR2 (20) DEFAULT 'ACTIVO' CHECK (
        ESTADO_PROVEEDOR IN (
            'ACTIVO',
            'INACTIVO',
            'BLOQUEADO'
        )
    )
);

-- 6. TABLA FACTURAS - Campos adicionales
ALTER TABLE FACTURAS
ADD (
    SUBTOTAL NUMBER (10, 2),
    DESCUENTO NUMBER (10, 2) DEFAULT 0,
    IMPUESTOS NUMBER (10, 2) DEFAULT 0,
    OBSERVACIONES CLOB,
    ESTADO_FACTURA VARCHAR2 (20) DEFAULT 'PENDIENTE' CHECK (
        ESTADO_FACTURA IN (
            'PENDIENTE',
            'PAGADA',
            'VENCIDA',
            'CANCELADA'
        )
    )
);

-- 7. TABLA PERSONAL - Campos adicionales para gestión
ALTER TABLE PERSONAL
ADD (
    FECHA_CONTRATACION DATE DEFAULT SYSDATE,
    ESTADO_EMPLEADO VARCHAR2 (20) DEFAULT 'ACTIVO' CHECK (
        ESTADO_EMPLEADO IN (
            'ACTIVO',
            'INACTIVO',
            'VACACIONES',
            'LICENCIA'
        )
    ),
    ESPECIALIDAD VARCHAR2 (100),
    NIVEL_EXPERIENCIA VARCHAR2 (20) CHECK (
        NIVEL_EXPERIENCIA IN (
            'JUNIOR',
            'INTERMEDIO',
            'SENIOR',
            'EXPERTO'
        )
    ),
    OBSERVACIONES CLOB
);

-- 8. TABLA SERVICIOS - Campos adicionales
ALTER TABLE SERVICIOS
ADD (
    DURACION_ESTIMADA NUMBER (3) DEFAULT 60, -- minutos
    NIVEL_DIFICULTAD VARCHAR2 (20) DEFAULT 'MEDIO' CHECK (
        NIVEL_DIFICULTAD IN (
            'FACIL',
            'MEDIO',
            'DIFICIL',
            'EXPERTO'
        )
    ),
    REQUIERE_CITA VARCHAR2 (1) DEFAULT 'S' CHECK (REQUIERE_CITA IN ('S', 'N')),
    ESTADO_SERVICIO VARCHAR2 (20) DEFAULT 'ACTIVO' CHECK (
        ESTADO_SERVICIO IN (
            'ACTIVO',
            'INACTIVO',
            'DESCONTINUADO'
        )
    ),
    OBSERVACIONES CLOB
);

-- 9. NUEVA TABLA: CONFIGURACION_SISTEMA
CREATE TABLE CONFIGURACION_SISTEMA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORIA VARCHAR2 (50) NOT NULL,
    CLAVE VARCHAR2 (100) NOT NULL,
    VALOR CLOB,
    DESCRIPCION VARCHAR2 (500),
    TIPO_DATO VARCHAR2 (20) DEFAULT 'STRING' CHECK (
        TIPO_DATO IN (
            'STRING',
            'NUMBER',
            'BOOLEAN',
            'DATE',
            'JSON'
        )
    ),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE DEFAULT SYSDATE,
    USUARIO_MODIFICACION VARCHAR2 (100),
    CONSTRAINT UK_CONFIG_CATEGORIA_CLAVE UNIQUE (CATEGORIA, CLAVE)
);

-- 10. NUEVA TABLA: HISTORIAL_CAMBIOS (Para auditoría)
CREATE TABLE HISTORIAL_CAMBIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLA_AFECTADA VARCHAR2 (100) NOT NULL,
    ID_REGISTRO NUMBER NOT NULL,
    TIPO_OPERACION VARCHAR2 (10) CHECK (
        TIPO_OPERACION IN ('INSERT', 'UPDATE', 'DELETE')
    ),
    DATOS_ANTERIORES CLOB,
    DATOS_NUEVOS CLOB,
    USUARIO VARCHAR2 (100),
    FECHA_CAMBIO DATE DEFAULT SYSDATE,
    IP_ADDRESS VARCHAR2 (50)
);

-- 11. NUEVA TABLA: NOTIFICACIONES
CREATE TABLE NOTIFICACIONES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID NUMBER,
    TITULO VARCHAR2 (200) NOT NULL,
    MENSAJE CLOB NOT NULL,
    TIPO VARCHAR2 (20) DEFAULT 'INFO' CHECK (
        TIPO IN (
            'INFO',
            'WARNING',
            'ERROR',
            'SUCCESS'
        )
    ),
    LEIDA VARCHAR2 (1) DEFAULT 'N' CHECK (LEIDA IN ('S', 'N')),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_LECTURA DATE,
    URL_ACCION VARCHAR2 (500)
);

-- 12. NUEVA TABLA: RESPALDOS_SISTEMA
CREATE TABLE RESPALDOS_SISTEMA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ARCHIVO VARCHAR2 (200) NOT NULL,
    RUTA_ARCHIVO VARCHAR2 (500) NOT NULL,
    TAMANO_ARCHIVO NUMBER,
    TIPO_RESPALDO VARCHAR2 (20) DEFAULT 'COMPLETO' CHECK (
        TIPO_RESPALDO IN (
            'COMPLETO',
            'INCREMENTAL',
            'DIFERENCIAL'
        )
    ),
    ESTADO VARCHAR2 (20) DEFAULT 'COMPLETADO' CHECK (
        ESTADO IN (
            'EN_PROCESO',
            'COMPLETADO',
            'ERROR'
        )
    ),
    FECHA_INICIO DATE DEFAULT SYSDATE,
    FECHA_FIN DATE,
    OBSERVACIONES CLOB,
    USUARIO_CREACION VARCHAR2 (100)
);

-- 13. Insertar configuraciones básicas del sistema
INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'EMPRESA',
        'NOMBRE',
        'TecnoTaller',
        'Nombre de la empresa',
        'STRING'
    );

INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'EMPRESA',
        'RUC',
        '',
        'RUC de la empresa',
        'STRING'
    );

INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'EMPRESA',
        'TELEFONO',
        '',
        'Teléfono principal',
        'STRING'
    );

INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'SISTEMA',
        'REGISTROS_POR_PAGINA',
        '25',
        'Registros mostrados por página',
        'NUMBER'
    );

INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'SISTEMA',
        'STOCK_MINIMO_ALERTA',
        '10',
        'Stock mínimo para alertas',
        'NUMBER'
    );

INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'OPERACIONES',
        'DURACION_CITA_DEFAULT',
        '60',
        'Duración por defecto de citas en minutos',
        'NUMBER'
    );

INSERT INTO
    CONFIGURACION_SISTEMA (
        CATEGORIA,
        CLAVE,
        VALOR,
        DESCRIPCION,
        TIPO_DATO
    )
VALUES (
        'SEGURIDAD',
        'INTENTOS_LOGIN_MAX',
        '3',
        'Máximo intentos de login fallidos',
        'NUMBER'
    );

-- 14. Crear índices para mejor rendimiento
CREATE INDEX IDX_CONFIGURACION_CATEGORIA ON CONFIGURACION_SISTEMA (CATEGORIA);

CREATE INDEX IDX_HISTORIAL_TABLA_ID ON HISTORIAL_CAMBIOS (TABLA_AFECTADA, ID_REGISTRO);

CREATE INDEX IDX_NOTIFICACIONES_USUARIO ON NOTIFICACIONES (USUARIO_ID, LEIDA);

CREATE INDEX IDX_RESPALDOS_FECHA ON RESPALDOS_SISTEMA (FECHA_INICIO);

-- 15. Comentarios en las tablas
COMMENT ON
TABLE CONFIGURACION_SISTEMA IS 'Configuraciones generales del sistema';

COMMENT ON
TABLE HISTORIAL_CAMBIOS IS 'Registro de cambios para auditoría';

COMMENT ON
TABLE NOTIFICACIONES IS 'Sistema de notificaciones para usuarios';

COMMENT ON
TABLE RESPALDOS_SISTEMA IS 'Registro de respaldos realizados';

COMMIT;