DESCRIBE clientes;
DESCRIBE TIPOS_CLIENTES;
DESCRIBE NACIONALIDADES;
-- ESTADO : ACTIVO O INACTIVO
SELECT 
  C.CLIENTE_ID,
  CONCAT(CONCAT(C.PRIMER_NOMBRE, ' '), C.SEGUNDO_NOMBRE) AS NOMBRES,
  CONCAT(CONCAT(C.PRIMER_APELLIDO, ' '), C.SEGUNDO_APELLIDO) AS APELLIDOS,
  C.TELEFONO,
  C.EMAIL,
  N.NOMBRE_NACIONALIDAD AS NACIONALIDAD,
  TP.DESCRIPCION_TIPO AS TIPO_CLIENTE,
  C.ESTADO
FROM CLIENTES C
LEFT JOIN NACIONALIDADES N ON C.NACIONALIDAD_ID = N.NACIONALIDAD_ID
LEFT JOIN TIPOS_CLIENTES TP ON C.TIPO_CLIENTE_ID = TP.TIPO_CLIENTE_ID;


ALTER TABLE CLIENTES
DROP CONSTRAINT CHK_ESTADO_CLIENTE;

ALTER TABLE CLIENTES
ADD CONSTRAINT estado_check
CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ELIMINADO'));